# route pour récupérer tous les catégories

GET http://localhost:3000/categories HTTP/1.1

###

POST http://localhost:3000/categories HTTP/1.1
content-type: application/json

{
    "route": "/C#",
    "label": "C#"
}

GET http://localhost:3000/posts HTTP/1.1
